### ISSUE TITLE
ADC interface is inadequate

### ISSUE THREAD

**Issue by tadziopazur** [Samsung/TizenRT#1001]
When reading from adc device, sample data format is determined by read request size.
The size of individual sample is derived by factors of request size (if size is divisible by 5 then, otherwise if size is divisible by 4, by 3, by 2..).
Reading just one byte delivers MSB of a sample, 2 bytes request (also 14, 22..) gives channel no. and MSB of a sample, 3-sized read (6, 9, 21..) gives channel no. and 16bits of data and so on.

First, the data format should not depend on the read size - it shall be the same (full record, that is channel no., data and all metadata), regardless if one reads by single bytes, or multiple samples at a time.

Second, there is no way to know when these samples were captured (timestamp is missing). Combined with the handling of internal ring buffer, client might get arbitrarily old data. Solution to this would be to deliver a timestamp (say uint32 of microseconds since last full hour) along each sample data.

Optionally, the interface is also missing calibration (which value is represents zero level), data format (i.e.: u32, s32, u16, s16 and so on) and channel selection. Are these of any value for the IoT-targeted RTOS?

**Comment by rzr** [comment]
calibration could be done at application level, no ? 
FTI, I've been using ADC with latest iotjs and it works for my simple case.
