### ISSUE TITLE
wifi app connection fails with 201 when providing ssid & passphrase in TASH

### ISSUE THREAD

**Issue by pholat** [Samsung/TizenRT#1189]
Trying to connect WiFI with tash `wifi` command with following setup:
`wifi startsta` -> reply success
`wifi connect MyNetwork MyPassphrase wpa2_aes` -> fails with error -201

Where 201 error in slsi_wifi_api.h is `SLSI_REASON_NETWORK_CONFIGURATION_NOT_FOUND` , whereas my understanding is it was provided in `wifi connect` command.

**Comment by pholat** [comment]
My bad, I've been providing data with typo. 

Though logs are a bit missleading in tash command : before connection there were ssid/passwd shown and when it failed there was written that empty ssid/passwd was provided, log:
`Connected to network: bssid: , ssid:
Join failed - reason 201`

**Comment by dr-venkman** [comment]
Could you please try as follows:

wifi join Network password wpa2_aes

**Comment by sunghan-chang** [comment]
@pholat Is it working with @dr-venkman 's suggestion?

**Comment by pholat** [comment]
@sunghan-chang My bad, it's working now - just log was misleading a bit. There was bad character copied into password and that's the error output.
