### ISSUE TITLE
No binary for Mac OS artik05x_AppCodesigner

### ISSUE THREAD

**Issue by pholat** [Samsung/TizenRT#1283]
CodeSigner tool can't be run on MacOS, so I can't work with Artik053s on Mac ( or Windows ), which in other parts of scripts is supported.

**Comment by sunghan-chang** [comment]
@pholat I am so sorry but that depends on chip vendor. Let's wait his response.

**Comment by JunhwanPark** [comment]
Hi @pholat ,
I prepared it. But I have not updated it yet. It will be updated before February is over. And then I'll tell you again.

**Comment by pholat** [comment]
Thanks, for now I'll try to deal with VB machine.

**Comment by sunghan-chang** [comment]
@pholat Could I leave a query to you? Do you use the TizenRT on MAC? Could you let me know any problem or difficulty?

**Comment by pholat** [comment]
@sunghan-chang Sure :) I've to work on Mac, there was some fun involved for me to i.e. use kconfig on mac, though nothing too serious. I can make PR to README with update how to install it.

While I couldn't configure ftdi driver on mac to have both jtag and uart available, I just use com on hardware uart0 instead - I believe it's common macbook problem. 

I've tried a few examples with ease.
In code documentation in form of readme.md is getting better and actually being helpful 👍 

To conclude my problems usually aren't macbook related :) 

I had two general concerns till now:
*  combination of bash scripts called from Make triggers a bit too many compilations and have some issues combined with ccache. 
*  it's possible to use c++ compiler, and that is great because it has more checks available etc. ( I actually depend on these ), I find adding any standard library troublesome due to headers conflicts.

All in all I didn't have much trouble and rather enjoy the platform.

**Comment by juitem** [comment]
It would be appreciated if you could contribute PR for MAC.
Actually we were also considering to support MAC officially on this year, if you proceed with submitting PRs and any additional supports we'll develop.
Thanks

**Comment by sunghan-chang** [comment]
@JunhwanPark Could you update supporting codeSigner for mac again? There is no relevant commit in SamsungARTIK.

**Comment by JunhwanPark** [comment]
@sunghan-chang Sorry. Update is delayed due to various issues. Please wait a little longer. The goal is to release a new version in mid-March.

**Comment by JunhwanPark** [comment]
@sunghan-chang https://github.com/SamsungARTIK/TizenRT/commit/de1e0c1aa02c7a0a3080a72a8c0001a8606855b1

**Comment by JunhwanPark** [comment]
Hi @pholat ,
I updated it. Enjoy~

**Comment by rzr** [comment]
For the record I think it can be download from SDK archive, is it for linux at least.

I can give more details if needed

**Comment by sunghan-chang** [comment]
@JunhwanPark Thank you for supporting.
@pholat I cherry-picked it from SamsungARTIK, ours is https://github.com/Samsung/TizenRT/commit/f61d3ff73aee0d72c96c9a14ef7a371020905ce0. If you configure MACOS as a host, codesigner for mac will be used automatically by download script.

**Comment by sunghan-chang** [comment]
@pholat If it is enough to this issue, let's close this.

**Comment by sunghan-chang** [comment]
@pholat Due to my fault (wrong modification on f61d3ff), I merged one more commit. https://github.com/Samsung/TizenRT/commit/5d8b5ab094ca1b5bcd8eed2dec21f827aaf29903. Sorry for inconvience.

**Comment by pholat** [comment]
@sunghan-chang No worries, thanks for fixing. I actually first moved onto Linux VM and now on linux PC entirely.

**Comment by sunghan-chang** [comment]
@pholat Ok, then I close this. If you have any issue on this, please reopen. Thank you for confirmation.
