### ISSUE TITLE
About CodeSigner tool for ARTIK 053s on ubuntu 32

### ISSUE THREAD

**Issue by maliyu** [Samsung/TizenRT#1360]
It seems CodeSigner tool in ARTIK 053s is for Ubuntu 64. Hence I can make successful compilation but fail on firmware downloading. Pls upload CodeSigner tool for ubuntu 32.

**Comment by sunghan-chang** [comment]
@maliyu Hello.
Already here is. https://github.com/Samsung/TizenRT/blob/master/build/configs/artik05x/tools/codesigner/linux32/artik05x_AppCodesigner
Doesn't it work? or not yet checked?

**Comment by maliyu** [comment]
Thank. I have not checked it.
