### ISSUE TITLE
How to build IoTivity in '/external/iotivity'?

### ISSUE THREAD

**Issue by DeseDad** [Samsung/TizenRT#143]
I found there are IoTivity code in '/external/iotivity' but it is not built even if I enabled it.
How can I build iotivity?

**Comment by lssgood** [comment]
That's an old version of IoTivity. We'll upload the latest verion by this Friday.
And We'll provide a basic guideline to build it.

**Comment by DeseDad** [comment]
Thanks  a lot

**Comment by JunhwanPark** [comment]
I also wanted to know this. I am expecting an update today.

**Comment by DeseDad** [comment]
Is there any update?

**Comment by lssgood** [comment]
@DeseDad You can check the PR-#155. Now, we're on the internal review process. After we're done with the review, we'll merge it.

**Comment by lssgood** [comment]
@DeseDad We merged it. If you don't have any more questions, please close this issue. Thanks.

**Comment by DeseDad** [comment]
Thanks a lot

**Comment by lssgood** [comment]
@DeseDad If you use iotivity build config(os/tools/.configure.sh artik053/iotivity), you can see 'simpleServer' TASH COMMAND to run the basic iotivity server.
Since we didn't include the tinycbor lib in the extlibs folder, it causes build error. We'll fix it.
