### ISSUE TITLE
How to connect to a router that requires 802.1x authentication?

### ISSUE THREAD

**Issue by zuowanbushiwo** [Samsung/TizenRT#1649]
Is there some example that can be referenced?

**Comment by sunghan-chang** [comment]
@pillip8282 Could you check and answer this?

**Comment by pillip8282** [comment]
Sorry for the late reply. TizenRT doesn't support 802.1x now. So you couldn't connect TizenRT to the router which supports 802.1x.

**Comment by zuowanbushiwo** [comment]
thanks, have any plan？

**Comment by pillip8282** [comment]
Unfortunately, we don't have a clear plan yet.
