### ISSUE TITLE
os/tools/mksmartfsimg.sh uses unexisting binary

### ISSUE THREAD

**Issue by pholat** [Samsung/TizenRT#1724]
There is no binary for nxfuse in repository, though scripts point to it.

**Comment by sunghan-chang** [comment]
@pholat Internally we use Nuttx's nxfuse but we don't support it now in public. I am so sorry but could you use Nuttx's nxfuse if you need to make smartfsimg?

**Comment by pholat** [comment]
@sunghan-chang Thanks, will do.
