### ISSUE TITLE
kernel/mqueue: g_desfree is not initialized!?

### ISSUE THREAD

**Issue by zhouxinhe** [Samsung/TizenRT#2163]
should we add `sq_init(&g_desfree);` in `void mq_initialize(void)`?

**Comment by jeongchanKim** [comment]
g_desfree is a global variable. So it will be initialized automatically.

**Comment by sunghan-chang** [comment]
@zhouxinhe Thank you for checking it.
@jeongchanKim Please confirm whether mqueue is not necessary to re-initialize or not.

**Comment by sunghan-chang** [comment]
Me and Jeongchan have checked it. There is no difference between adding sq_init and keeping now. But it looks strange because other lists are initialized with sq_init at mq_initiailize function. Let's keep current code.
@zhouxinhe If you have different opinion, please let us know.

**Comment by zhouxinhe** [comment]
I faced a bss region corruption issue days ago, crash happened when traversing this queue `g_desfree`...
I checked and found it's not initialized with sq_init (so I opened this issue). 
Now I have found the root cause, which is not related to g_desfree initialization.
I will close this issue, thanks for checking.
