### ISSUE TITLE
`iotivity_config.h` file should be removed with `make clean` command

### ISSUE THREAD

**Issue by JunhwanPark** [Samsung/TizenRT#2464]
```bash
os/tools$ sh configure.sh artik053s/st_things
os$ make
os$ make clean
os$ find .. -name "iotivity_config.h"
../framework/src/st_things/things_stack/iotivity_config.h
../external/iotivity/iotivity_1.2-rel/resource/c_common/iotivity_config.h
```

* `../framework/src/st_things/things_stack/iotivity_config.h`
This file exists in the st_things framework. Is this file required here?
After I deleted this file and rebuild it, I did not get any errors.

* `../external/iotivity/iotivity_1.2-rel/resource/c_common/iotivity_config.h`
This file is created when iotivity is built. It must be removed with the `make clean` command.

**Comment by SenthilKumarGS** [comment]
@harish-191
Check this issue.

**Comment by harish-191** [comment]
I resolved the issue and created the PR<https://github.com/Samsung/TizenRT/pull/2497/files>.

**Comment by harish-191** [comment]
PR has been merged.

**Comment by SenthilKumarGS** [comment]
@harish-191,
Close this issue.

**Comment by JunhwanPark** [comment]
@SenthilKumarGS @harish-191 
I checked it. Thank you.
