### ISSUE TITLE
Kernel debug logs not working in NXP

### ISSUE THREAD

**Issue by kishore-sn** [Samsung/TizenRT#2870]
Hi, 
When I use imxrt1050-evk/nxp_demo config and enable kernel logging, then the board fails to boot up. No logs are coming on serial console. 

I have enabled below configs:
#
# Debug Options
#
CONFIG_DEBUG=y
CONFIG_DEBUG_ERROR=y

**Comment by kishore-sn** [comment]
@HarrisonChoi750405 Can you please help with this issue. 
If kernel logs are disabled, there is no way to debug any issue.

**Comment by sunghan-chang** [comment]
@HarrisonChoi750405 Hello. We face an issue with debug message enabled.

**Comment by sunghan-chang** [comment]
This was modified.
