### ISSUE TITLE
What is the automated way to build release|debug from a single config?

### ISSUE THREAD

**Issue by tadziopazur** [Samsung/TizenRT#290]
In nuttx, the flag is R: one wants to build release, they invoke:
nuttx/os$ make R=1
or 
nuttx/os$ make R=0

In TizenRT config system (Kconfig files, seen thru menuconfig make target) there are several flags, including:
DEBUG_SYMBOLS  DEBUG_FULLOPT  DEBUG_NOOPT  DEBUG_CUSTOM.
Some of them are not used in the build process (DEBUG_FULLOPT is not used at all).
The sources are built using ARCHOPTIMIZATION and MAXOPTIMIZATION, which are inconsistently set in Make.defs files (i.e.: some set MAXOPTIMIZATION to -O0).

How can one build TizenRT with consistent debug/release flags without changing sources (Make.defs)?

**Comment by sunghan-chang** [comment]
We have a plan to support that functionality but not now.

**Comment by sunghan-chang** [comment]
@tadziopazur I can not find R option on nuttx Makefile. Only V treated. Could you tell me where do you find it?

**Comment by sunghan-chang** [comment]
@tadziopazur
