### ISSUE TITLE
Two same files in esp_idf_port

### ISSUE THREAD

**Issue by sunghan-chang** [Samsung/TizenRT#3196]
Hello.

There are two `eap_common.c` in esp_idf_port.
Because of that, it shows below

```
make[2]: Entering directory '/home/sunghan/Work/TinyAra/Forked_TizenRT/external/esp_idf_port'
Makefile:138: target 'esp32_eap_common.o' given more than once in the same rule
```

When esp_idf_port is built, one of file will be overlapped.
Please check this.

**Comment by sunghan-chang** [comment]
@SRCN-LiQin @zhouxinhe @ChinaTizenRT @xiarihf @xixidodo @glb1013 Could you check this?

**Comment by ChinaTizenRT** [comment]
we check this issue, it does., thanks.
