### ISSUE TITLE
Does tizenrt support command "cpuinfo", or some other command such as "cpuinfo"?

### ISSUE THREAD

**Issue by cooldo** [Samsung/TizenRT#329]

**Comment by cooldo** [comment]
I want to get the cpu information by command line.
How can I get this information?
Thank you very much.
Your response will be deeply thanks.

**Comment by jeongarmy** [comment]
I don't know what cpu information means exactly?
you mean /proc/cpuinfo which show somethings like model name, processor in linux?
Please let me know what you want to know using this command exactly and why.

**Comment by cooldo** [comment]
Thank you very much for your response.   
We want to use the command such as linux "top", to print the cpu usage of each process. 
we are designing "system log" IDE,  our purpose is to capture the system log from "tash", and display into our IDE graphicly.
Thank you very much.

**Comment by jeongarmy** [comment]
I'm sorry that we don't support that function now.
But you can get them from proc file system.
You can get cpu usage of each process by reading /proc/[pid]/loadavg.
We will consider whether to support command like top in linux or not.

**Comment by cooldo** [comment]
Thank you very much, it is very helpful.
