### ISSUE TITLE
can't load the emulator from the IDE tizen studio.

### ISSUE THREAD

**Issue by ping996** [Samsung/TizenRT#3591]
I can't load the emulator from the tizen studio when click the tools->emulator managers.
error: could not create the java virtual machine. it can't find the org.tizen.device.manager.Main,
I also can't find this jar package in all installed directory.
I use the open JDK 10 and set the JAVA_HOME and path OK by input java -version in cmd.
what's problems?

**Comment by sunghan-chang** [comment]
@ping996 Sorry for late reply. Let us check it first.

**Comment by hasw7569** [comment]
@ping996
Are you using Tizen RT IDE ?
To check this issue, I installed the Tizen RT IDE.
However, I did not find the emulator manager in the tools menu.

If you using Tizen RT IDE, what board are you using ?

In addition, the following link provides a debugging guide. Have you followed this guide?
https://developer.tizen.org/development/tizen-studio/rt-ide/getting-started/debugging-project

**Comment by ping996** [comment]
@hasw7569  I installed the tizen studio, not the RT version.  now It's working now by changed some setting of my window 10 system.

**Comment by sunghan-chang** [comment]
@ping996 Actually we have separated RT IDE in tizen studio. Please refer @hasw7569 's link and let us know when you have an issue.
