### ISSUE TITLE
Does TizenRT support ARM Cortex-M33?

### ISSUE THREAD

**Issue by prashantrar** [Samsung/TizenRT#3716]
I read the porting guide document " TizenRT/docs/HowToAddnewBoard.md "

There is a line in there that states: "Currently, TizenRT supports only ARM architecture with armv7-m, armv7-r and common folders."

Does this mean that TizenRT cannot be ported to other arm architectures. I am specifically concerned about Cortex-M33

**Comment by sunghan-chang** [comment]
@prashantrar Hello. It means that currently we support only them (Actually we support xtensa architecture as well). It does not mean "cannot be ported". We were already using Cortex-M33 in internal project.

**Comment by sangam-swami** [comment]
As mentioned TizenRT can be ported to other arm architectures, Specifically we using Cortex-M33 internally without security extension support as of now.

**Comment by prashantrar** [comment]
Hello All, Thanks for the clarification, I am closing this issue now.
