### ISSUE TITLE
Regarding TizenRT git log format.

### ISSUE THREAD

**Issue by ChinaTizenRT** [Samsung/TizenRT#3796]
When typing "git log" in TizenRT,  much similar commit shows:
"Merge pull request #xxx  from xxx", 
normally this commit can't be be seen in other open source.
I wonder why keeping it in git log history, is there any advantage.
otherwise PR can be merged via button "Rebase and merge" 
instead of default "Merge pull request" in githhub merge page.
it seems that above log "Merge pull request #xxx  from xxx" will disappear.

**Comment by sunghan-chang** [comment]
@ChinaTizenRT Thank you for good suggestion. Actually I don't like it eigher but it was a suggetion of SW engineering team introduced github. Let's discuss it internally.

**Comment by sunghan-chang** [comment]
@ChinaTizenRT Thank you for good suggestion. We decided using 3rd option you said.
