### ISSUE TITLE
Missing stddef.h in iotbus_spi.h

### ISSUE THREAD

**Issue by pmarcinkiew** [Samsung/TizenRT#397]
The SPI IoTBus header:
https://github.com/Samsung/TizenRT/blob/master/framework/include/iotbus/iotbus_spi.h

It is missing definition for size_t header _stddef.h_. It requires developer to include _stdlib.h_ or _stddef.h_.

Please see our travis build log for reference:

https://travis-ci.org/Samsung/iotjs/jobs/263522465

I can modify iotbus_spi.h to include missing headers.

What is your opinion about this solution?

**Comment by sunghan-chang** [comment]
@pmarcinkiew Thank you for notice problem.
*<sys/types.h>* should be included for *size_t*. But in iotbus_spi.c includes stdlib.h which includes sys/types.h. So, it does not show any compilation error. (Actually this is wrong, so we will fix it)
Do you include iotbus_spi.h on your source codes?

**Comment by sunghan-chang** [comment]
Please refer #401 .

**Comment by sunghan-chang** [comment]
@pmarcinkiew #401 was merged. If you don't have any additional question, let's close this.
