### ISSUE TITLE
Can't launch TizenRT studio!!!

### ISSUE THREAD

**Issue by HotCodeworker** [Samsung/TizenRT#4014]
I just installed the TizenRT IDE using Tizen Studio 3.5 with RT IDE installer:[https://developer.tizen.org/development/tizen-studio/download](https://developer.tizen.org/development/tizen-studio/download)

However, I can't launch the RT IDE such as below attached picture:
![tizenRT-err1](https://user-images.githubusercontent.com/11155677/68533528-44deeb80-036d-11ea-8067-a7a2dfeed000.png)

I was going to attach the log file after zipping it, too:

[log.zip](https://github.com/Samsung/TizenRT/files/3827603/log.zip)

Let us know how to fix it and thanks in advance.

**Comment by HotCodeworker** [comment]
In addition, I installed openJDK such as follows: [https://developer.tizen.org/development/articles/openjdk-and-openjfx-installation-guide](https://developer.tizen.org/development/articles/openjdk-and-openjfx-installation-guide)

**Comment by HotCodeworker** [comment]
When using oracle JDK, this issue could be solved. This issue might happen when using openJDK.

**Comment by manishtr** [comment]
Hi,
RT ide does not support OpenJDK or Java 12.
You need to use java 8.
Please try to install and use a new workspace.
Regards,
Manish

**Comment by sunghan-chang** [comment]
@HotCodeworker I am sorry for inconvenient. We will add the sentence to say Java 8 in guidance.

**Comment by manishtr** [comment]
I have raised the PR for Documentation update at https://github.com/Samsung/tizen-docs/pull/937

**Comment by sunghan-chang** [comment]
@HotCodeworker In prerequisites of Tizen Studio, we added the **NOTE** to say above.
https://developer.tizen.org/development/tizen-studio/download/prerequisites
>Note
>For RT IDE use Oracle Java Development Kit (JDK) 8 only.

If you have any problem to use RT IDE, please let us know.
