### ISSUE TITLE
Support of RT IDE on esp32 board?

### ISSUE THREAD

**Issue by HotCodeworker** [Samsung/TizenRT#4015]
I'm using on ESP32 board and RT IDE.
On RT IDE, I used "Batch build project".
However, I can not use the function like "Application Manager" and "Kernel config" because RT IDE might not enable the functions.

Originally, the functions should be enabled as next links:[https://developer.tizen.org/development/tizen-studio/rt-ide/getting-started/managing-project](https://developer.tizen.org/development/tizen-studio/rt-ide/getting-started/managing-project)

then please let me know how and what.

**Comment by zhouxinhe** [comment]
Hello HotCodeworker

To use `Application Manager` and `Kernel Config` function:
1. Select the project in the Project Explorer view.
2. Click the arrow next to the Build TizenRT Project icon.
  Then you can see `Application Manager` and `Kernel Config` items  in the drop-down menu.

I tried to select `Application Manager`, but no dialog appeared (I don't know why...).
Fortunately, we can manage application in `Kernel Config` -> Application Configuration -> ...

**Comment by sunghan-chang** [comment]
> I tried to select Application Manager, but no dialog appeared (I don't know why...).

Let me check it.

**Comment by HotCodeworker** [comment]
In addition, my issue are only about ESP32_DevKit board.
More issue with ESP32_DevKit board is also that I couldn't debug with this ESP32 board on RT IDE beacuse RT IDE poped-up like that "there is no debug.xml".

**Comment by sunghan-chang** [comment]
@manishtr When we check `make applist` or `dbuild.sh applist`, it creates .appSpec file. Could you check why it does not work with Application Manager?

**Comment by dkdwivedi** [comment]
launching Application manager creates same .appSpec file as generated by `make applist`

**Comment by sunghan-chang** [comment]
@dkdwivedi Thank you for helping.
@HotCodeworker  This is resolved with https://github.com/Samsung/TizenRT/commit/572d61278e226b5e32e3a8cdd244fd9fd1bd0ce8. After checking Application Manager on IDE, let you know at next Monday.

**Comment by sunghan-chang** [comment]
@HotCodeworker
1. Application Manager is working now with latest commit.
2. As you said, debug feature is under implementation. Let's talk it in #4029 .

Currently kerne config and application manager are working well. Let's close this and when you have a problem, let me know. Thank you for the issue.
