### ISSUE TITLE
Support on ESP32-DevKitC board?

### ISSUE THREAD

**Issue by HotCodeworker** [Samsung/TizenRT#4016]
I was compiling on ESP32-DevKitC board.
Then when we selected download option and performed it using "./dbuild downlaod", the error occured like this: "there is no esptool.py under the /home/hotcoder/git/TizenRT/build/tools/esp32/esptool_py/esptool"

I think the file, esptool.py was NOT created after compiling and building using "ESP32-DevKitC board" configuration on terminal invoked by "./dbuild.sh".

Then please let me know why and thanks in advance.

**Comment by xiarihf** [comment]
Dear HotCodeworker, the esptool.py is the submodule of TizenRT due to the license, so please get the submodules first by using following git command.
            git submodule update --init --recursive 
We will add a checking operation before downloading images soon.
Thanks for your feedback.

**Comment by HotCodeworker** [comment]
Thanks for your reply and I've solve it.
