### ISSUE TITLE
No memory information after building project on ESP32_DevKitC board.

### ISSUE THREAD

**Issue by HotCodeworker** [Samsung/TizenRT#4031]
The log are as follows after build project.

-------------------------------------------------------------------------------------
....
make[1]: Leaving directory '/root/tizenrt/framework'
make[1]: Entering directory '/root/tizenrt/os/arch/xtensa/src'
make[2]: Entering directory '/root/tizenrt/os/board/esp32_devkit/src'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/root/tizenrt/os/board/esp32_devkit/src'
LD: tinyara
make[1]: Leaving directory '/root/tizenrt/os/arch/xtensa/src'
CP: tinyara.elf.bin
Start the Board Specific Work for Binary
######################################
######################################
	.data 	.bss 	.text 	 Total
[STATUS] SUCCEED

--------------------------------------------------------------------------------------

Then there is no memory information on above log with "Libray Sizes" label.
This issue happened on both RT IDE and CLI on terminal.

**Comment by sunghan-chang** [comment]
@xixidodo Could you assign the person to check this?
@HotCodeworker Currently we support showing libraries size for GNU toolchain. But esp32's toolchain is not GNU so that we need to check it.

**Comment by xixidodo** [comment]
@HotCodeworker @sunghan-chang 
Currently,  @ChinaTizenRT  is checking this now,  xtensa toolchain is not same, we need to check why stat is not retrieved.

**Comment by ChinaTizenRT** [comment]
@HotCodeworker, internally job is done for this feature, after review, patch will be released.

**Comment by sunghan-chang** [comment]
@HotCodeworker PR #4048 , commit 2f58ee7cd74970f7a4ccbb7fa6869e5a8168219a was merged. With latest codes, it prints libraries information. If you have any issue on it, please let us know.
