### ISSUE TITLE
Does Tizen RT support ARM Cortex-M4?

### ISSUE THREAD

**Issue by leemgs** [Samsung/TizenRT#4184]
Recently, I checked the board and ARM CPU list that are supported by Tizen RT at the below webpage. When I try to use ARM Cortex-M4 and 256Kb RAM, does Tizen RT support this hardware? Or, Do you have a plan to append the CPU list such as ARM Cortex-M4? 
    
* https://github.com/Samsung/TizenRT#supported-board--emulator
   * ARTIK053 
   * ARTIK053S 
   * ARTIK055S 
   * CY4390X 
   * ESP32-DevKitC 
   * ESP-WROVER-KIT 
   * iMX RT 1020 EVK 
   * iMX RT 1050 EVK 
   * SIDK_S5JT200 
   * STM32F407-DISC1 
   * STM32F429I-DISCO 
   * STM32L4R9AI-DISCO 
   * QEMU 
* https://github.com/Samsung/TizenRT/tree/master/os/arch/arm/src 
   * armv7-m, armv7-r, bcm4390x, imxrt, s5j, stm32, stm3214, tiva

**Comment by sunghan-chang** [comment]
Hello @leemgs .
CortexM4 is the ARM v7m family so that you can use the hardware you said with current source codes. For your information, stm series we support have CM4.
