### ISSUE TITLE
Which Kconfig has the entry of "NET_LWIP_DHCPC" ?

### ISSUE THREAD

**Issue by manoharahk** [Samsung/TizenRT#423]
https://github.com/Samsung/TizenRT/blob/d8b91b34e2ce2fc8b42644806c27bb39c2446ac2/apps/examples/wakaama_client/wakaama_client.c#L45

**Comment by sinzah** [comment]
As I knew, there are no entry to configure NET_LWIP_DHCPC.
CONFIG_NETUTILS_DHCPC is used to dhcp client instead lwip dhcp

**Comment by pillip8282** [comment]
Yes he is right. TizenRT doesn't use CONFIG_NETUTILS_DHCPC anymore.

**Comment by sunghan-chang** [comment]
@manoharahk Do you have additional question? If you don't, let's close this.

**Comment by manoharahk** [comment]
OK, then are we creating missing entry to configure?

**Comment by sunghan-chang** [comment]
@manoharahk Just removing that line is enough. There is no config NET_LWIP_DHCPC and we will not use that one.

**Comment by manoharahk** [comment]
OK. Thanks you all for your responses on this issue.
