### ISSUE TITLE
ERROR: arch/arm/Kconfig

### ISSUE THREAD

**Issue by Boooooots** [Samsung/TizenRT#4243]
There is a spelling error at line 194: 	not 'defaut n' , should be 'default n'

**Comment by sunghan-chang** [comment]
@Boooooots You're right. Thank you for information. Will you raise a PR for it or do you want to modify by ourself?

**Comment by sunghan-chang** [comment]
@Boooooots I've made the PR for this. Thank you for the issue.

**Comment by sunghan-chang** [comment]
@Boooooots It was merged. When you have another issue, please fill free to contact us. Thank you.
