### ISSUE TITLE
Longjmp, setjmp crashes TizenRT

### ISSUE THREAD

**Issue by pmarcinkiew** [Samsung/TizenRT#461]
The setjmp and longjmp are used in JerryScript error handling for JavaScript errors:

https://github.com/jerryscript-project/jerryscript/blob/master/jerry-core/parser/js/common.h#L118

This causes crash of TizenRT.

**Comment by sunghan-chang** [comment]
Girish is under reviewing for this.

**Comment by girishks2000** [comment]
was this tested with setjmp patch

**Comment by pmarcinkiew** [comment]
We tested https://github.com/Samsung/TizenRT/pull/462 with IoT.js. It requires several patches from other repositories (JerryScript, libtuv) so @tadziopazur take over my change with https://github.com/Samsung/TizenRT/pull/576

**Comment by sunghan-chang** [comment]
That was merged so that I close this.
