### ISSUE TITLE
GCC 7.2.0 compilation failure - double_t

### ISSUE THREAD

**Issue by pmarcinkiew** [Samsung/TizenRT#463]
When compiling with Linux toolchain, there are build errors like:

    math/lib_j1.c: In function ‘pone’:
    math/lib_j1.c:363:2: error: unknown type name ‘double_t’; did you mean
    ‘double’?
      double_t z;
      ^~~~~~~~

**Comment by sunghan-chang** [comment]
#464 was merged.
