### ISSUE TITLE
UDP broadcast not supported

### ISSUE THREAD

**Issue by pmarcinkiew** [Samsung/TizenRT#478]
TizenRT doesn't implement UDP broadcast:

https://github.com/Samsung/TizenRT/blob/master/os/net/lwip/src/api/sockets.c#L2203

It is used in IoT.js test suite:
https://github.com/Samsung/iotjs/blob/master/test/run_pass/test_dgram_broadcast.js#L70

**Comment by sunghan-chang** [comment]
This is duplicated with #881 so that I close this. Please follow this there.
