### ISSUE TITLE
I2C_TRANSFER description is inaccurate

### ISSUE THREAD

**Issue by tadziopazur** [Samsung/TizenRT#480]
The documentation for I2C_TRANSFER (include/tinyara/i2c.h) states:
 *   Perform a sequence of I2C transfers, each transfer is started with a
 *   START and the final transfer is completed with a STOP. Each sequence
 *   will be an 'atomic'  operation in the sense that any other I2C actions
 *   will be serialized and pend until this read completes. Optional.

Since S5J implements it, it should follow the specification. This one doesn't.
1. Start/stop depends on sequence length/message length (it should not)
2. try_address does not care for HW errors (hsi2c_stop/hsic_start call hsi2c_wait_xfer_done and do not check the return value), result being multiple start/stop commands get issued

**Comment by rzr** [comment]
May relate to:
https://github.com/Samsung/TizenRT/issues/322
