### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by chaima-elbahraoui** [Samsung/TizenRT#5862]
Hello, I'm encountering some build issues after following the HowToSetEnv file. 

Running make produces the following output: 
![image](https://github.com/Samsung/TizenRT/assets/86025581/a889622c-6a53-4e5c-ba34-bc6268a82d71)
Please direct me for any possible solution. Thank you!

**Comment by ewoodev** [comment]
please Could you let me know board/config your selected?

**Comment by chaima-elbahraoui** [comment]
Hello, thank you for replying. It was imxrt1020-evk/SAM. However, I have issues even with other board/config.

**Comment by ewoodev** [comment]
How about use tizenrt docker image instead of HowToSetEnv?

**Comment by chaima-elbahraoui** [comment]
Yes it works that way. Thank you
