### ISSUE TITLE
cannot boot after flash all

### ISSUE THREAD

**Issue by qdk0901** [Samsung/TizenRT#63]
Hi,
 I compile TizenRT for s5jt200 board and flash all binary into the board, but the board can't boot up after flashing, and the serial keep ouputing
`UUUUUUUUCB02000016061010170220100000001000000000000000000000FF00000000000000000000000000170B00019A9B51EFCB00098207F0030FC9C804069BBDF5B6FDD6C7F3ZZZZZZZZ`
 after reset

**Comment by girishks2000** [comment]
@qdk0901 
This is because the binary is built with write protection enabled. So before you flash the binary please disable the write protection with "sudo ./openocd_linux64 -f disable_write_protect.cfg"
Later run the flash all script. it will work.

**Comment by qdk0901** [comment]
thanks very much， it works
