### ISSUE TITLE
pdfs under "docs/API_Reference" does not open

### ISSUE THREAD

**Issue by ravisankarg** [Samsung/TizenRT#930]
pdf files under "docs/API_Reference" does not open!

**Comment by lokeshbv** [comment]
Hi @ravisankarg, github does not support previewing of pdf files. So you need to download and view it.

**Comment by ravisankarg** [comment]
I tried to read the docs after cloning.

**Comment by ravisankarg** [comment]
Just to make it clear, issue is not with github preview.

**Comment by sunghan-chang** [comment]
@ravisankarg I am so sorry. Those aren't opened due to our security system. After merging doxygen config, we will re-upload them.

**Comment by sunghan-chang** [comment]
@ravisankarg I raise html instead of pdf. That is better to use. Could you check it?
