### ISSUE TITLE
integer overflow error

### ISSUE THREAD

**Issue by ravisankarg** [Samsung/TizenRT#962]
I was just curious & browsing the malloc code and found a possible int overflow error. i have not yet explored a way to write test codes and test my self w/o a need for a board etc. I am guessing, undesired things would happen when overflow happens. So, just leaving the pointers to the code location. an expert can check more.

size = MM_ALIGN_UP(size + SIZEOF_MM_ALLOCNODE);
at line no# 125 in os/mm/mm_heap/mm_malloc.c

**Comment by sunghan-chang** [comment]
@ravisankarg This is resolved by Jeongchan's #986 . Thank you.
